---
- name: install iis web
  hosts: windows
  tasks:
    - name: install iis 
      win_feature:
        name: Web-Server
        state: present

    - name: start iis service
      win_service:
        name: W3Svc
        state: started

    - name: create web index.html
      win_copy:
        content: "{{  iis_test_message  }}"
        dest: C:\Inetpub\wwwroot\index.html

    - name: show web
      debug:
        msg: "http://{{ ansible_host }}"